// Code generated by protoc-gen-go. DO NOT EDIT.
// source: judy.proto

package judy

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Heartbeat struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	CommandOutput        string   `protobuf:"bytes,3,opt,name=CommandOutput,proto3" json:"CommandOutput,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a8885cde79d710, []int{0}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

func (m *Heartbeat) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Heartbeat) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *Heartbeat) GetCommandOutput() string {
	if m != nil {
		return m.CommandOutput
	}
	return ""
}

type HeartbeatResponse struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	MessageId            string   `protobuf:"bytes,2,opt,name=MessageId,proto3" json:"MessageId,omitempty"`
	Command              string   `protobuf:"bytes,3,opt,name=Command,proto3" json:"Command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartbeatResponse) Reset()         { *m = HeartbeatResponse{} }
func (m *HeartbeatResponse) String() string { return proto.CompactTextString(m) }
func (*HeartbeatResponse) ProtoMessage()    {}
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_96a8885cde79d710, []int{1}
}

func (m *HeartbeatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartbeatResponse.Unmarshal(m, b)
}
func (m *HeartbeatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartbeatResponse.Marshal(b, m, deterministic)
}
func (m *HeartbeatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartbeatResponse.Merge(m, src)
}
func (m *HeartbeatResponse) XXX_Size() int {
	return xxx_messageInfo_HeartbeatResponse.Size(m)
}
func (m *HeartbeatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartbeatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HeartbeatResponse proto.InternalMessageInfo

func (m *HeartbeatResponse) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *HeartbeatResponse) GetMessageId() string {
	if m != nil {
		return m.MessageId
	}
	return ""
}

func (m *HeartbeatResponse) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func init() {
	proto.RegisterType((*Heartbeat)(nil), "judy.Heartbeat")
	proto.RegisterType((*HeartbeatResponse)(nil), "judy.HeartbeatResponse")
}

func init() { proto.RegisterFile("judy.proto", fileDescriptor_96a8885cde79d710) }

var fileDescriptor_96a8885cde79d710 = []byte{
	// 146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2a, 0x4d, 0xa9,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xb2, 0xb9, 0x38, 0x3d, 0x52,
	0x13, 0x8b, 0x4a, 0x92, 0x52, 0x13, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x9c, 0x73, 0x32, 0x53, 0xf3,
	0x4a, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x19, 0x2e, 0x4e,
	0xdf, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0xcf, 0x14, 0x09, 0x26, 0xb0, 0x24, 0x42, 0x40, 0x48,
	0x85, 0x8b, 0xd7, 0x39, 0x3f, 0x37, 0x37, 0x31, 0x2f, 0xc5, 0xbf, 0xb4, 0xa4, 0xa0, 0xb4, 0x44,
	0x82, 0x19, 0xac, 0x02, 0x55, 0x50, 0x29, 0x9d, 0x4b, 0x10, 0x6e, 0x59, 0x50, 0x6a, 0x71, 0x41,
	0x7e, 0x5e, 0x71, 0x2a, 0x05, 0x96, 0x4a, 0x70, 0xb1, 0x43, 0xcd, 0x87, 0x5a, 0x07, 0xe3, 0x26,
	0xb1, 0x81, 0xbd, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xcd, 0xc3, 0xe9, 0xfa, 0xf0, 0x00,
	0x00, 0x00,
}
